### ISSUE TITLE
Update to lastest version

### ISSUE THREAD

**Issue by gajotnt** [lbalker/iocage-plugin-unificontroller#1]
The plugin is at Version: 5.11.50, latest version is 5.12.35 :)

I know version 11.3 of freenas is still on Beta/RC :)

**Comment by lbalker** [comment]
As far as I'm aware, the package is still pulled from http://pkg.cdn.trueos.org/iocage/unstable which has 5.12.35. There's no unifi controller version encoded in the plugin at all.
